plugins:
  typst: true

filters:
  comments: true

rules:
  ja-hiragana-keishikimeishi: true
  ja-hiragana-fukushi: true
  ja-hiragana-hojodoushi: true
  preset-ja-technical-writing:
    no-mix-dearu-desumasu:
      preferInBody: "である"
      "preferInList": "である"
    # 変数や数値をカンマ区切りにすることが多いため無効化
    # 日本語の読点の数の制限は有効
    max-comma: false
    max-kanji-continuous-len: false
    sentence-length:
      max: 100
      skipPatterns:
        - "/^\\$[\\s\\S]*?\\$$/m" # 数式段落
    ja-no-mixed-period:
      periodMark: "．"
      allowPeriodMarks: []
  prh:
    rulePaths:
      - ./.textlint_prh.yml
